#!/bin/zsh
aws s3api create-bucket \
  --acl public-read \
  --bucket woodneck-vectors.painkillergis.com

aws s3api put-bucket-cors \
  --bucket woodneck-vectors.painkillergis.com \
  --cors-configuration file://devops/s3-cors-configuration.json

aws s3api put-bucket-policy \
  --bucket woodneck-vectors.painkillergis.com \
  --policy file://devops/s3-bucket-policy.json

aws s3api put-bucket-website \
  --bucket woodneck-vectors.painkillergis.com \
  --website-configuration file://devops/s3-website-configuration.json