#!/bin/zsh
aws acm request-certificate \
  --domain-name woodneck-vectors.painkillergis.com \
  --validation-method DNS | \
  jq .CertificateArn -r | tr -d '\n' > devops/aws:acm/certificate-arn

resourceRecord=""
while [ "$resourceRecord" = "" ] ; do
  description=$(aws acm describe-certificate --certificate-arn file://devops/aws:acm/certificate-arn)
  resourceRecord=$(echo $description | jq ".Certificate.DomainValidationOptions[].ResourceRecord")
done

name=$(echo $resourceRecord | jq ".Name" -r)
type=$(echo $resourceRecord | jq ".Type" -r)
value=$(echo $resourceRecord | jq ".Value" -r)
changeBatch=$(jq "
.Changes[].ResourceRecordSet.Name=\"$name\"
  | .Changes[].ResourceRecordSet.Type=\"$type\"
  | .Changes[].ResourceRecordSet.ResourceRecords[].Value=\"$value\"
" devops/aws:acm/validate-dns.json)
aws route53 change-resource-record-sets \
  --hosted-zone-id Z020039932WR8OUOBOALI \
  --change-batch file://<(echo $changeBatch)

aws acm wait certificate-validated --certificate-arn file://devops/aws:acm/certificate-arn