#!/bin/zsh
distributionConfig=$(jq "
.CallerReference=\"`uuidgen`\"
  | .ViewerCertificate.ACMCertificateArn=\"`cat devops/aws:acm/certificate-arn`\"
  " devops/aws:cloudfront/distribution-config.json)
aws cloudfront create-distribution \
  --distribution-config file://<(echo $distributionConfig) | \
  jq .Distribution.Id -r | tr -d '\n' > devops/aws:cloudfront/distribution-id